### ISSUE TITLE
[urgent] backend: fix lambda function

### ISSUE THREAD

**Issue by chinmaykunkikar** [chinmaykunkikar/vide-amplify#19]
Apparently the title is being split into an array with space `' '` delimiter.
```log
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                                                   message                                                                                                   |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| START RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2 Version: $LATEST                                                                                                                                      |
| Unknown options: an,appropriate,size,shirt,in,clothing,storage.mp4,/tmp/                                                                                                                                    |
| mkdir: cannot create directory ‘takes’: Read-only file system                                                                                                                                               |
| Unknown options: an,appropriate,size,shirt,in,clothing,storage/,s3://vide103713-staging/public/output/0f8bb51c-ce82-43be-9745-2d77eaf7db28/Consultant,takes,an,appropriate,size,shirt,in,clothing,storage/  |
| [ERROR] TypeError: 'RootLogger' object is not callable Traceback (most recent call last):   File "/var/task/index.py", line 59, in handler     logger("Successfully transcoded")                            |
| END RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2                                                                                                                                                         |
| REPORT RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2 Duration: 1974.72 ms Billed Duration: 1975 ms Memory Size: 2048 MB Max Memory Used: 99 MB Init Duration: 141.63 ms                                   |
| START RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2 Version: $LATEST                                                                                                                                      |
| Unknown options: an,appropriate,size,shirt,in,clothing,storage.mp4,/tmp/                                                                                                                                    |
| mkdir: cannot create directory ‘takes’: Read-only file system                                                                                                                                               |
| Unknown options: an,appropriate,size,shirt,in,clothing,storage/,s3://vide103713-staging/public/output/0f8bb51c-ce82-43be-9745-2d77eaf7db28/Consultant,takes,an,appropriate,size,shirt,in,clothing,storage/  |
| [ERROR] TypeError: 'RootLogger' object is not callable Traceback (most recent call last):   File "/var/task/index.py", line 59, in handler     logger("Successfully transcoded")                            |
| END RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2                                                                                                                                                         |
| REPORT RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2 Duration: 1700.66 ms Billed Duration: 1701 ms Memory Size: 2048 MB Max Memory Used: 100 MB                                                           |
| START RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2 Version: $LATEST                                                                                                                                      |
| Unknown options: an,appropriate,size,shirt,in,clothing,storage.mp4,/tmp/                                                                                                                                    |
| mkdir: cannot create directory ‘takes’: Read-only file system                                                                                                                                               |
| Unknown options: an,appropriate,size,shirt,in,clothing,storage/,s3://vide103713-staging/public/output/0f8bb51c-ce82-43be-9745-2d77eaf7db28/Consultant,takes,an,appropriate,size,shirt,in,clothing,storage/  |
| [ERROR] TypeError: 'RootLogger' object is not callable Traceback (most recent call last):   File "/var/task/index.py", line 59, in handler     logger("Successfully transcoded")                            |
| END RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2                                                                                                                                                         |
| REPORT RequestId: beb81d72-df07-46f3-a831-6d3d8f9a1fc2 Duration: 1744.63 ms Billed Duration: 1745 ms Memory Size: 2048 MB Max Memory Used: 100 MB                                                           |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by chinmaykunkikar** [comment]
There is a way to handle this in the transcoder function.
The best scenario is to preserve the title and filenames all the way..

Looking forward to reopen this issue for code maintenance and improvements.
